### ISSUE TITLE
screensize notification on top right and error messages

### ISSUE THREAD

**Issue by djthor** [fcojgodoy/teruterubozu#4]
Hello

I published a website with your theme, but it gives a lot of errors.

First of all on the top rigt corner you see a notification about the device i.e. for example: 'mobile > 320px (20em)'

And second I get a lot of errors when saving a page or a post.
One of the error messages is: 
Warning: Cannot modify header information - headers already sent by (output started at /home/djthor/public_html/wp-content/themes/teruterubozu/inc/enqueue.php:1) in /home/djthor/public_html/wp-admin/includes/misc.php on line 1126

Let me know if you will fix this or I will have to change theme.
My website is: www.dj-thor.dance

Cheers

**Comment by fcojgodoy** [comment]
Hello

First, thanks for the report.

I will fix the errors. Tomorrow I will work on it.

Sorry for the inconvenience.

**Comment by fcojgodoy** [comment]
Hello again,

I can not reproduce the warning "Warning: Cannot modify header inform...".
Could I know a couple of things?:
- Does the error/warning occur only in posts or pages with embedded YouTube videos?
- How do you include the video in the post or page (share/insert Youtube option, with a plugin)?

**Comment by fcojgodoy** [comment]
Do not worry about the previous questions. I think I've already found the problem. Tomorrow I will update the theme.

**Comment by djthor** [comment]
I could give you admin rights if you wish?

Op di 7 aug. 2018 23:11 schreef Francisco Godoy <notifications@github.com>:

**Comment by fcojgodoy** [comment]
Tomorrow is sure to update the theme and almost certain that the problem will be solved.
But if you create an administrator user with my email, I will update the theme and check that everything goes well.
My email is hola@franciscogodoy.es

**Comment by djthor** [comment]
ok you will be receiving an email with your login details
username: francisco

Op wo 8 aug. 2018 om 00:38 schreef Francisco Godoy <notifications@github.com

**Comment by fcojgodoy** [comment]
The new update is now uploaded. If you want you can update it to see if it fixes the errors.

**Comment by djthor** [comment]
It is not possible to update it. I get error messages.
Do you still have the login?
Yesterday I completely uninstalled it and reinstalled the whole website but
still I get error messages.
Is it compatible with the latest wordpress?
What kind of PHP version are you using?

Op wo 8 aug. 2018 om 09:24 schreef Francisco Godoy <notifications@github.com

**Comment by fcojgodoy** [comment]
I did not receive the mail. Maybe you did not check the 'send email' box? Can you try again?

I tested the theme with the latest WordPress and from PHP 5.3 to 7.x. :confused:

**Comment by djthor** [comment]
username: francisco
password: bF@x@e*NQI(Ma8NOXXla5WEz

Op wo 8 aug. 2018 om 11:04 schreef Francisco Godoy <notifications@github.com

**Comment by fcojgodoy** [comment]
Ok, I'm login and I have the pass in my email box.

**Comment by fcojgodoy** [comment]
I don't see any problem.
- The theme new version (0.2.9) is installed correctly.
- I have created (and removed) posts and pages with and without embedded video (also in streaming) and no error is printed.

I have installed the Query Monitor plugin, which print in the admin bar warnings and errors. Can you try again and tell me if this plugin print some warning or error?

**Comment by djthor** [comment]
Okay it seems like the errors are gone now indeed.
But I still have this creen size message in the right corner top (see
attachement)

Op wo 8 aug. 2018 om 12:43 schreef Francisco Godoy <notifications@github.com

**Comment by fcojgodoy** [comment]
I think that the screen size message appears to you because it is cached in the browser you are using.
Try Ctrl+F5 to recharge the page.

**Comment by djthor** [comment]
great that solved it
Thanks a lot for your help!!!

Op wo 8 aug. 2018 om 13:23 schreef Francisco Godoy <notifications@github.com
